# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c79ccf84663adbd5c6dc2a86ada654b65c1623c0806c120a70e354365b3ebf4f9468a464930b3e99fc372e218673f59bd8eedff52978d263d8567e130bfa2895

test:
  secret_key_base: 22e06d781c74446d40f34439ac336cfea4fb851291d7f1f79983d8cfe1c18be7ee6d76b955ae807efd27e214b621f264e69f1076b5d9db840ccf69087f4ae9ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
